const exercises = [
  // CHEST
  {
    exerciseId: 'bench-press',
    name: 'Bench Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    description: 'Classic compound chest exercise performed on a flat bench.',
    instructions: [
      'Lie flat on a bench with feet on the floor',
      'Grip the bar slightly wider than shoulder-width',
      'Unrack and lower the bar to mid-chest',
      'Press the bar back up to lockout',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BBBenchPress',
  },
  {
    exerciseId: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    description: 'Upper chest focused pressing movement on an inclined bench.',
    instructions: [
      'Set bench to 30-45 degree incline',
      'Press dumbbells up from shoulder level',
      'Lower with control to chest level',
      'Keep feet flat on the floor',
    ],
    tags: ['push', 'compound', 'upper-chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralClavicular/DBInclineBenchPress',
  },
  {
    exerciseId: 'cable-flyes',
    name: 'Cable Flyes',
    category: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    description: 'Isolation chest exercise using cable machine for constant tension.',
    instructions: [
      'Set cables at shoulder height',
      'Step forward with slight lean',
      'Bring hands together in hugging motion',
      'Squeeze chest at the peak, return slowly',
    ],
    tags: ['push', 'isolation', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/CBStandingFly',
  },
  {
    exerciseId: 'dumbbell-chest-press',
    name: 'Dumbbell Chest Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    description: 'Flat bench press using dumbbells for greater range of motion.',
    instructions: [
      'Lie flat on bench with dumbbells at chest level',
      'Press dumbbells up until arms are extended',
      'Lower slowly to starting position',
      'Keep core engaged throughout',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/DBBenchPress',
  },
  {
    exerciseId: 'dumbbell-flyes',
    name: 'Dumbbell Flyes',
    category: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    description: 'Isolation movement for chest stretch and contraction.',
    instructions: [
      'Lie flat on bench with dumbbells above chest',
      'Lower arms out to the sides in a wide arc',
      'Keep slight bend in elbows throughout',
      'Squeeze chest to bring dumbbells back together',
    ],
    tags: ['push', 'isolation', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/DBFly',
  },
  {
    exerciseId: 'push-ups',
    name: 'Push-Ups',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: 'bodyweight',
    description: 'Fundamental bodyweight exercise for chest and pushing strength.',
    instructions: [
      'Start in plank position with hands shoulder-width apart',
      'Lower body until chest nearly touches the floor',
      'Push back up to full arm extension',
      'Keep core tight and body in a straight line',
    ],
    tags: ['push', 'compound', 'chest', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BWPushup',
  },
  {
    exerciseId: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine',
    description: 'Machine-guided pressing for controlled chest work.',
    instructions: [
      'Adjust seat so handles are at chest level',
      'Grip handles and press forward',
      'Extend arms without locking elbows',
      'Return slowly to starting position',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/LVChestPress',
  },
  {
    exerciseId: 'decline-bench-press',
    name: 'Decline Bench Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    description: 'Bench press on decline targeting lower chest fibers.',
    instructions: [
      'Lie on decline bench and hook feet under pads',
      'Grip the bar slightly wider than shoulder-width',
      'Lower bar to lower chest',
      'Press back up to lockout',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BBDeclineBenchPress',
  },

  // SHOULDERS
  {
    exerciseId: 'overhead-press',
    name: 'Overhead Press',
    category: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'barbell',
    description: 'Standing barbell press overhead for shoulder development.',
    instructions: [
      'Stand with feet shoulder-width apart',
      'Hold bar at shoulder level with overhand grip',
      'Press bar overhead to full lockout',
      'Lower bar back to shoulders with control',
    ],
    tags: ['push', 'compound', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/BBMilitaryPress',
  },
  {
    exerciseId: 'lateral-raises',
    name: 'Lateral Raises',
    category: 'shoulders',
    secondaryMuscles: ['traps'],
    equipment: 'dumbbell',
    description: 'Isolation exercise targeting the lateral deltoid.',
    instructions: [
      'Stand with dumbbells at your sides',
      'Raise arms out to the sides until parallel',
      'Keep slight bend in elbows',
      'Lower slowly with control',
    ],
    tags: ['push', 'isolation', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidLateral/DBLateralRaise',
  },
  {
    exerciseId: 'front-raises',
    name: 'Front Raises',
    category: 'shoulders',
    secondaryMuscles: ['chest'],
    equipment: 'dumbbell',
    description: 'Isolation exercise targeting the anterior deltoid.',
    instructions: [
      'Stand with dumbbells in front of thighs',
      'Raise one arm to shoulder height',
      'Lower slowly and alternate arms',
      'Keep core engaged and avoid swinging',
    ],
    tags: ['push', 'isolation', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/DBAlternatingFrontRaise',
  },
  {
    exerciseId: 'arnold-press',
    name: 'Arnold Press',
    category: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    description: 'Rotating shoulder press hitting all three deltoid heads.',
    instructions: [
      'Start with dumbbells at chest level, palms facing you',
      'Rotate palms outward as you press overhead',
      'Reverse the motion on the way down',
      'Keep movement controlled throughout',
    ],
    tags: ['push', 'compound', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/DBArnoldPress',
  },
  {
    exerciseId: 'face-pulls',
    name: 'Face Pulls',
    category: 'shoulders',
    secondaryMuscles: ['traps', 'back'],
    equipment: 'cable',
    description: 'Cable exercise targeting rear delts and upper back.',
    instructions: [
      'Set cable at face height with rope attachment',
      'Pull rope toward face, separating hands',
      'Squeeze rear delts and upper back',
      'Return slowly to starting position',
    ],
    tags: ['pull', 'isolation', 'rear-delts', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidPosterior/CBStandingRearDeltRowRope',
  },
  {
    exerciseId: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    description: 'Seated or standing shoulder press with dumbbells for balanced development.',
    instructions: [
      'Hold dumbbells at shoulder height, palms forward',
      'Press dumbbells overhead until arms are extended',
      'Lower back to shoulder level with control',
      'Keep core engaged throughout',
    ],
    tags: ['push', 'compound', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/DBShoulderPress',
  },
  {
    exerciseId: 'reverse-flyes',
    name: 'Reverse Flyes',
    category: 'shoulders',
    secondaryMuscles: ['traps', 'back'],
    equipment: 'dumbbell',
    description: 'Dumbbell exercise targeting posterior deltoids.',
    instructions: [
      'Bend forward at the hips with slight knee bend',
      'Hold dumbbells below chest with palms facing each other',
      'Raise arms out to the sides squeezing rear delts',
      'Lower with control to starting position',
    ],
    tags: ['pull', 'isolation', 'rear-delts', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidPosterior/DBSeatedRearLateralRaise',
  },

  // TRICEPS
  {
    exerciseId: 'tricep-pushdowns',
    name: 'Tricep Pushdowns',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    description: 'Cable exercise isolating the triceps.',
    instructions: [
      'Stand facing cable machine with rope or bar attachment',
      'Keep elbows pinned to your sides',
      'Push the weight down until arms are fully extended',
      'Return slowly to starting position',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/CBPushdown',
  },
  {
    exerciseId: 'tricep-dips',
    name: 'Tricep Dips',
    category: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'bodyweight',
    description: 'Compound bodyweight exercise for triceps.',
    instructions: [
      'Grip parallel bars and support your weight',
      'Lower body by bending elbows to 90 degrees',
      'Keep body upright to target triceps',
      'Press back up to starting position',
    ],
    tags: ['push', 'compound', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/BWBenchDip',
  },
  {
    exerciseId: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Overhead extension targeting the long head of the triceps.',
    instructions: [
      'Hold dumbbell overhead with both hands',
      'Lower behind head by bending elbows',
      'Extend arms back to starting position',
      'Keep upper arms stationary throughout',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/DBOneArmTriExtBench',
  },
  {
    exerciseId: 'skull-crushers',
    name: 'Skull Crushers',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    description: 'Lying triceps extension with barbell for heavy tricep loading.',
    instructions: [
      'Lie on flat bench holding barbell with narrow grip',
      'Lower bar toward forehead by bending elbows',
      'Keep upper arms perpendicular to floor',
      'Extend arms back to starting position',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/BBLyingTriExt',
  },
  {
    exerciseId: 'tricep-kickbacks',
    name: 'Tricep Kickbacks',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Dumbbell exercise isolating the triceps in a bent-over position.',
    instructions: [
      'Bend over with one hand on bench for support',
      'Hold dumbbell with upper arm parallel to floor',
      'Extend forearm back until arm is straight',
      'Squeeze tricep at top, lower with control',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/DBKickback',
  },

  // BACK
  {
    exerciseId: 'deadlift',
    name: 'Deadlift',
    category: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'core', 'traps'],
    equipment: 'barbell',
    description: 'Full body compound lift focusing on the posterior chain.',
    instructions: [
      'Stand with feet hip-width, bar over mid-foot',
      'Hinge at hips and grip bar outside knees',
      'Drive through feet, extending hips and knees',
      'Stand tall at top, then lower with control',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/ErectorSpinae/BBDeadlift',
  },
  {
    exerciseId: 'pull-ups',
    name: 'Pull-Ups',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'bodyweight',
    description: 'Classic bodyweight exercise for lat and back development.',
    instructions: [
      'Hang from bar with overhand grip, slightly wider than shoulders',
      'Pull body up until chin clears the bar',
      'Lower with control to full extension',
      'Avoid swinging or kipping',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/BWPullup',
  },
  {
    exerciseId: 'barbell-rows',
    name: 'Barbell Rows',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms', 'core'],
    equipment: 'barbell',
    description: 'Bent-over row for overall back thickness.',
    instructions: [
      'Hinge forward at hips with slight knee bend',
      'Pull bar to lower chest/upper abdomen',
      'Squeeze shoulder blades together at top',
      'Lower with control, maintaining back position',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/BBBentOverRow',
  },
  {
    exerciseId: 'lat-pulldowns',
    name: 'Lat Pulldowns',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'cable',
    description: 'Cable exercise targeting the latissimus dorsi.',
    instructions: [
      'Sit at lat pulldown machine with thighs secured',
      'Grip bar wider than shoulder-width',
      'Pull bar to upper chest, squeezing lats',
      'Return to full extension with control',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/CBFrontPulldown',
  },
  {
    exerciseId: 'seated-cable-rows',
    name: 'Seated Cable Rows',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'cable',
    description: 'Seated rowing movement for mid-back development.',
    instructions: [
      'Sit with feet on platform, knees slightly bent',
      'Pull handle to lower chest',
      'Squeeze shoulder blades together',
      'Return with control, allowing stretch',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/CBSeatedRow',
  },
  {
    exerciseId: 'dumbbell-rows',
    name: 'Dumbbell Rows',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'dumbbell',
    description: 'One-arm row for unilateral back development.',
    instructions: [
      'Place one hand and knee on bench for support',
      'Hold dumbbell with free hand, arm extended',
      'Pull dumbbell to hip, squeezing shoulder blade',
      'Lower with control to full extension',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/DBBentOverRow',
  },
  {
    exerciseId: 'chin-ups',
    name: 'Chin-Ups',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'bodyweight',
    description: 'Underhand grip pull-up emphasizing biceps and lower lats.',
    instructions: [
      'Hang from bar with underhand (supinated) grip',
      'Pull body up until chin clears the bar',
      'Focus on squeezing lats and biceps',
      'Lower with control to full extension',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/BWUnderhandChinup',
  },

  // BICEPS
  {
    exerciseId: 'bicep-curls',
    name: 'Bicep Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    description: 'Classic isolation exercise for bicep development.',
    instructions: [
      'Stand with dumbbells at sides, palms forward',
      'Curl weights to shoulder level',
      'Squeeze biceps at the top',
      'Lower slowly to full extension',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/DBCurl',
  },
  {
    exerciseId: 'hammer-curls',
    name: 'Hammer Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    description: 'Bicep curl variation targeting the brachialis and forearms.',
    instructions: [
      'Hold dumbbells with neutral grip (palms facing each other)',
      'Curl weights to shoulder level',
      'Keep elbows stationary at sides',
      'Lower with control',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Brachioradialis/DBHammerCurl',
  },
  {
    exerciseId: 'barbell-curls',
    name: 'Barbell Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    description: 'Heavy compound curl using barbell for maximum bicep loading.',
    instructions: [
      'Stand with barbell, underhand grip at shoulder width',
      'Curl bar to shoulder height',
      'Keep upper arms stationary',
      'Lower with control to full extension',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/BBCurl',
  },
  {
    exerciseId: 'incline-dumbbell-curls',
    name: 'Incline Dumbbell Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    description: 'Curl on incline bench for greater bicep stretch under load.',
    instructions: [
      'Sit on incline bench set to 45 degrees',
      'Let arms hang straight down with dumbbells',
      'Curl weights up while keeping upper arms stationary',
      'Lower slowly to full stretch',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/DBInclineCurl',
  },
  {
    exerciseId: 'cable-curls',
    name: 'Cable Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    description: 'Cable curl providing constant tension throughout the range of motion.',
    instructions: [
      'Stand facing cable machine with bar attachment at low position',
      'Grip bar with underhand grip at shoulder width',
      'Curl bar up toward shoulders',
      'Lower with control, maintaining tension',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/CBCurl',
  },
  {
    exerciseId: 'concentration-curls',
    name: 'Concentration Curls',
    category: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Seated single-arm curl for peak bicep contraction.',
    instructions: [
      'Sit on bench with legs apart',
      'Rest elbow against inner thigh',
      'Curl dumbbell up squeezing bicep at top',
      'Lower slowly with full control',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Brachialis/DBConcentrationCurl',
  },

  // QUADRICEPS
  {
    exerciseId: 'squats',
    name: 'Squats',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    description: 'The king of leg exercises for overall lower body development.',
    instructions: [
      'Position bar on upper back, feet shoulder-width',
      'Break at hips and knees simultaneously',
      'Descend until thighs are parallel or below',
      'Drive through feet to stand back up',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BBSquat',
  },
  {
    exerciseId: 'leg-press',
    name: 'Leg Press',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    description: 'Machine exercise for heavy quadricep loading.',
    instructions: [
      'Sit in leg press machine with back flat against pad',
      'Place feet shoulder-width on platform',
      'Lower platform by bending knees to 90 degrees',
      'Press back up without locking knees',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/SL45LegPress',
  },
  {
    exerciseId: 'bulgarian-split-squats',
    name: 'Bulgarian Split Squats',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    description: 'Single-leg squat variation for balanced leg development.',
    instructions: [
      'Place rear foot on bench behind you',
      'Hold dumbbells at sides',
      'Lower until front thigh is parallel to floor',
      'Drive through front heel to stand',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BBSingleLegSplitSquat',
  },
  {
    exerciseId: 'leg-extensions',
    name: 'Leg Extensions',
    category: 'quadriceps',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Machine isolation exercise for quadricep definition.',
    instructions: [
      'Sit in machine with back against pad',
      'Hook ankles under roller pad',
      'Extend legs until straight',
      'Lower with control, avoid letting weight stack slam',
    ],
    tags: ['legs', 'isolation', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/LVLegExtension',
  },
  {
    exerciseId: 'front-squats',
    name: 'Front Squats',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'barbell',
    description: 'Front-loaded squat emphasizing quads and upright torso.',
    instructions: [
      'Rest barbell across front deltoids with crossed arms or clean grip',
      'Keep elbows high and chest up throughout',
      'Squat down until thighs are parallel or below',
      'Drive through feet to stand, maintaining upright torso',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BBFrontSquat',
  },
  {
    exerciseId: 'lunges',
    name: 'Lunges',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    description: 'Walking or stationary lunge for unilateral leg strength.',
    instructions: [
      'Hold dumbbells at sides, stand tall',
      'Step forward into a lunge position',
      'Lower back knee toward floor',
      'Push through front foot to return or step forward',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/DBLunge',
  },
  {
    exerciseId: 'hack-squats',
    name: 'Hack Squats',
    category: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    description: 'Machine squat variation for focused quad development.',
    instructions: [
      'Position shoulders under pads, feet shoulder-width on platform',
      'Release safety handles',
      'Lower by bending knees to 90 degrees',
      'Press back up through feet',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/SLHackSquat',
  },

  // HAMSTRINGS
  {
    exerciseId: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    description: 'Hip hinge movement focusing on hamstring stretch and load.',
    instructions: [
      'Hold barbell with overhand grip at hip level',
      'Hinge at hips, pushing them backward',
      'Lower bar along legs until hamstring stretch is felt',
      'Drive hips forward to return to standing',
    ],
    tags: ['legs', 'compound', 'hamstrings'],
    referenceUrl: 'https://exrx.net/WeightExercises/OlympicLifts/RomanianDeadlift',
  },
  {
    exerciseId: 'leg-curls',
    name: 'Leg Curls',
    category: 'hamstrings',
    secondaryMuscles: ['calves'],
    equipment: 'machine',
    description: 'Machine isolation exercise for hamstring development.',
    instructions: [
      'Lie face down on leg curl machine',
      'Hook heels under roller pad',
      'Curl weight by bending knees',
      'Lower with control to starting position',
    ],
    tags: ['legs', 'isolation', 'hamstrings'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/LVLyingLegCurl',
  },
  {
    exerciseId: 'seated-leg-curls',
    name: 'Seated Leg Curls',
    category: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Seated machine curl for hamstring isolation.',
    instructions: [
      'Sit in machine with back against pad',
      'Position pad above heels, legs extended',
      'Curl legs down by bending knees',
      'Return slowly to starting position',
    ],
    tags: ['legs', 'isolation', 'hamstrings'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/LVSeatedLegCurl',
  },
  {
    exerciseId: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    category: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'dumbbell',
    description: 'Dumbbell variation of the RDL for hamstring and glute work.',
    instructions: [
      'Hold dumbbells at thighs with neutral grip',
      'Hinge at hips pushing them backward',
      'Lower dumbbells along legs keeping back flat',
      'Drive hips forward to return to standing',
    ],
    tags: ['legs', 'compound', 'hamstrings'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/DBStrBackStrLegDeadlift',
  },

  // CALVES
  {
    exerciseId: 'calf-raises',
    name: 'Calf Raises',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Standing calf raise for calf muscle development.',
    instructions: [
      'Stand on calf raise machine with balls of feet on platform',
      'Lower heels below platform for full stretch',
      'Rise up on toes as high as possible',
      'Squeeze at top, lower with control',
    ],
    tags: ['legs', 'isolation', 'calves'],
    referenceUrl: 'https://exrx.net/WeightExercises/Gastrocnemius/LVStandingCalfRaise',
  },
  {
    exerciseId: 'seated-calf-raises',
    name: 'Seated Calf Raises',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Seated calf raise targeting the soleus muscle.',
    instructions: [
      'Sit in seated calf raise machine with knees under pad',
      'Place balls of feet on platform edge',
      'Lower heels for full stretch',
      'Push up through toes and squeeze at top',
    ],
    tags: ['legs', 'isolation', 'calves'],
    referenceUrl: 'https://exrx.net/WeightExercises/Soleus/LVSeatedCalfRaise',
  },
  {
    exerciseId: 'leg-press-calf-raises',
    name: 'Leg Press Calf Raises',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Calf raise performed on the leg press machine for heavy loading.',
    instructions: [
      'Sit in leg press with balls of feet on lower edge of platform',
      'Keep legs nearly straight',
      'Push through toes extending ankles',
      'Lower heels back for full stretch',
    ],
    tags: ['legs', 'isolation', 'calves'],
    referenceUrl: 'https://exrx.net/WeightExercises/Gastrocnemius/SL45CalfPress',
  },

  // GLUTES
  {
    exerciseId: 'hip-thrusts',
    name: 'Hip Thrusts',
    category: 'glutes',
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: 'barbell',
    description: 'Barbell hip thrust for maximum glute activation.',
    instructions: [
      'Sit on floor with upper back against bench',
      'Roll barbell over hips with pad',
      'Drive hips up until body forms straight line',
      'Squeeze glutes at top, lower with control',
    ],
    tags: ['legs', 'compound', 'glutes'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/BBHipThrust',
  },
  {
    exerciseId: 'cable-kickbacks',
    name: 'Cable Kickbacks',
    category: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'cable',
    description: 'Cable hip extension for targeted glute isolation.',
    instructions: [
      'Attach ankle cuff to low cable',
      'Face the machine holding frame for support',
      'Kick leg backward squeezing glute at top',
      'Return slowly to starting position',
    ],
    tags: ['legs', 'isolation', 'glutes'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/CBStandingHipExtension',
  },

  // CORE
  {
    exerciseId: 'plank',
    name: 'Plank',
    category: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    description: 'Isometric core exercise for stability and endurance.',
    instructions: [
      'Get in push-up position on forearms',
      'Keep body in straight line from head to heels',
      'Engage core and hold position',
      'Breathe steadily throughout',
    ],
    tags: ['core', 'isometric', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWFrontPlank',
  },
  {
    exerciseId: 'cable-crunches',
    name: 'Cable Crunches',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'cable',
    description: 'Weighted crunch using cable for progressive overload on abs.',
    instructions: [
      'Kneel facing cable machine with rope attachment',
      'Hold rope behind head',
      'Crunch downward, bringing elbows toward knees',
      'Return to starting position with control',
    ],
    tags: ['core', 'isolation', 'abs'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/CBKneelingCrunch',
  },
  {
    exerciseId: 'stability-ball-crunches',
    name: 'Stability Ball Crunches',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Crunches on a stability ball for increased range of motion.',
    instructions: [
      'Lie back on stability ball with feet flat on floor',
      'Place hands behind head or across chest',
      'Crunch up contracting abs',
      'Lower back over ball for full stretch',
    ],
    tags: ['core', 'isolation', 'abs'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWBallCrunch',
  },
];

module.exports = exercises;
