const exercises = [
  // CHEST
  {
    exerciseId: 'bench-press',
    name: 'Bench Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    description: 'Classic compound chest exercise performed on a flat bench.',
    instructions: [
      'Lie flat on a bench with feet on the floor',
      'Grip the bar slightly wider than shoulder-width',
      'Unrack and lower the bar to mid-chest',
      'Press the bar back up to lockout',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BBBenchPress',
  },
  {
    exerciseId: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    description: 'Upper chest focused pressing movement on an inclined bench.',
    instructions: [
      'Set bench to 30-45 degree incline',
      'Press dumbbells up from shoulder level',
      'Lower with control to chest level',
      'Keep feet flat on the floor',
    ],
    tags: ['push', 'compound', 'upper-chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralClavicular/DBInclineBenchPress',
  },
  {
    exerciseId: 'cable-flyes',
    name: 'Cable Flyes',
    category: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    description: 'Isolation chest exercise using cable machine for constant tension.',
    instructions: [
      'Set cables at shoulder height',
      'Step forward with slight lean',
      'Bring hands together in hugging motion',
      'Squeeze chest at the peak, return slowly',
    ],
    tags: ['push', 'isolation', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/CBStandingFly',
  },
  {
    exerciseId: 'dumbbell-chest-press',
    name: 'Dumbbell Chest Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    description: 'Flat bench press using dumbbells for greater range of motion.',
    instructions: [
      'Lie flat on bench with dumbbells at chest level',
      'Press dumbbells up until arms are extended',
      'Lower slowly to starting position',
      'Keep core engaged throughout',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/DBBenchPress',
  },
  {
    exerciseId: 'dumbbell-flyes',
    name: 'Dumbbell Flyes',
    category: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    description: 'Isolation movement for chest stretch and contraction.',
    instructions: [
      'Lie flat on bench with dumbbells above chest',
      'Lower arms out to the sides in a wide arc',
      'Keep slight bend in elbows throughout',
      'Squeeze chest to bring dumbbells back together',
    ],
    tags: ['push', 'isolation', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/DBFly',
  },
  {
    exerciseId: 'push-ups',
    name: 'Push-Ups',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: 'bodyweight',
    description: 'Fundamental bodyweight exercise for chest and pushing strength.',
    instructions: [
      'Start in plank position with hands shoulder-width apart',
      'Lower body until chest nearly touches the floor',
      'Push back up to full arm extension',
      'Keep core tight and body in a straight line',
    ],
    tags: ['push', 'compound', 'chest', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BWPushup',
  },
  {
    exerciseId: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'machine',
    description: 'Machine-guided pressing for controlled chest work.',
    instructions: [
      'Adjust seat so handles are at chest level',
      'Grip handles and press forward',
      'Extend arms without locking elbows',
      'Return slowly to starting position',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/LVChestPress',
  },
  {
    exerciseId: 'decline-bench-press',
    name: 'Decline Bench Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    description: 'Bench press on decline targeting lower chest fibers.',
    instructions: [
      'Lie on decline bench and hook feet under pads',
      'Grip the bar slightly wider than shoulder-width',
      'Lower bar to lower chest',
      'Press back up to lockout',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BBDeclineBenchPress',
  },

  // SHOULDERS
  {
    exerciseId: 'overhead-press',
    name: 'Overhead Press',
    category: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'barbell',
    description: 'Standing barbell press overhead for shoulder development.',
    instructions: [
      'Stand with feet shoulder-width apart',
      'Hold bar at shoulder level with overhand grip',
      'Press bar overhead to full lockout',
      'Lower bar back to shoulders with control',
    ],
    tags: ['push', 'compound', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/BBMilitaryPress',
  },
  {
    exerciseId: 'lateral-raises',
    name: 'Lateral Raises',
    category: 'shoulders',
    secondaryMuscles: ['traps'],
    equipment: 'dumbbell',
    description: 'Isolation exercise targeting the lateral deltoid.',
    instructions: [
      'Stand with dumbbells at your sides',
      'Raise arms out to the sides until parallel',
      'Keep slight bend in elbows',
      'Lower slowly with control',
    ],
    tags: ['push', 'isolation', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidLateral/DBLateralRaise',
  },
  {
    exerciseId: 'front-raises',
    name: 'Front Raises',
    category: 'shoulders',
    secondaryMuscles: ['chest'],
    equipment: 'dumbbell',
    description: 'Isolation exercise targeting the anterior deltoid.',
    instructions: [
      'Stand with dumbbells in front of thighs',
      'Raise one arm to shoulder height',
      'Lower slowly and alternate arms',
      'Keep core engaged and avoid swinging',
    ],
    tags: ['push', 'isolation', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/DBAlternatingFrontRaise',
  },
  {
    exerciseId: 'arnold-press',
    name: 'Arnold Press',
    category: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    description: 'Rotating shoulder press hitting all three deltoid heads.',
    instructions: [
      'Start with dumbbells at chest level, palms facing you',
      'Rotate palms outward as you press overhead',
      'Reverse the motion on the way down',
      'Keep movement controlled throughout',
    ],
    tags: ['push', 'compound', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/DBArnoldPress',
  },
  {
    exerciseId: 'face-pulls',
    name: 'Face Pulls',
    category: 'shoulders',
    secondaryMuscles: ['traps', 'back'],
    equipment: 'cable',
    description: 'Cable exercise targeting rear delts and upper back.',
    instructions: [
      'Set cable at face height with rope attachment',
      'Pull rope toward face, separating hands',
      'Squeeze rear delts and upper back',
      'Return slowly to starting position',
    ],
    tags: ['pull', 'isolation', 'rear-delts', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidPosterior/CBStandingRearDeltRowRope',
  },
  {
    exerciseId: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    description: 'Seated or standing shoulder press with dumbbells for balanced development.',
    instructions: [
      'Hold dumbbells at shoulder height, palms forward',
      'Press dumbbells overhead until arms are extended',
      'Lower back to shoulder level with control',
      'Keep core engaged throughout',
    ],
    tags: ['push', 'compound', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/DBShoulderPress',
  },
  {
    exerciseId: 'reverse-flyes',
    name: 'Reverse Flyes',
    category: 'shoulders',
    secondaryMuscles: ['traps', 'back'],
    equipment: 'dumbbell',
    description: 'Dumbbell exercise targeting posterior deltoids.',
    instructions: [
      'Bend forward at the hips with slight knee bend',
      'Hold dumbbells below chest with palms facing each other',
      'Raise arms out to the sides squeezing rear delts',
      'Lower with control to starting position',
    ],
    tags: ['pull', 'isolation', 'rear-delts', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidPosterior/DBSeatedRearLateralRaise',
  },

  // TRICEPS
  {
    exerciseId: 'tricep-pushdowns',
    name: 'Tricep Pushdowns',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    description: 'Cable exercise isolating the triceps.',
    instructions: [
      'Stand facing cable machine with rope or bar attachment',
      'Keep elbows pinned to your sides',
      'Push the weight down until arms are fully extended',
      'Return slowly to starting position',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/CBPushdown',
  },
  {
    exerciseId: 'tricep-dips',
    name: 'Tricep Dips',
    category: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'bodyweight',
    description: 'Compound bodyweight exercise for triceps.',
    instructions: [
      'Grip parallel bars and support your weight',
      'Lower body by bending elbows to 90 degrees',
      'Keep body upright to target triceps',
      'Press back up to starting position',
    ],
    tags: ['push', 'compound', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/BWBenchDip',
  },
  {
    exerciseId: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Overhead extension targeting the long head of the triceps.',
    instructions: [
      'Hold dumbbell overhead with both hands',
      'Lower behind head by bending elbows',
      'Extend arms back to starting position',
      'Keep upper arms stationary throughout',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/DBOneArmTriExtBench',
  },
  {
    exerciseId: 'skull-crushers',
    name: 'Skull Crushers',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    description: 'Lying triceps extension with barbell for heavy tricep loading.',
    instructions: [
      'Lie on flat bench holding barbell with narrow grip',
      'Lower bar toward forehead by bending elbows',
      'Keep upper arms perpendicular to floor',
      'Extend arms back to starting position',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/BBLyingTriExt',
  },
  {
    exerciseId: 'tricep-kickbacks',
    name: 'Tricep Kickbacks',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Dumbbell exercise isolating the triceps in a bent-over position.',
    instructions: [
      'Bend over with one hand on bench for support',
      'Hold dumbbell with upper arm parallel to floor',
      'Extend forearm back until arm is straight',
      'Squeeze tricep at top, lower with control',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/DBKickback',
  },

  // BACK
  {
    exerciseId: 'deadlift',
    name: 'Deadlift',
    category: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'core', 'traps'],
    equipment: 'barbell',
    description: 'Full body compound lift focusing on the posterior chain.',
    instructions: [
      'Stand with feet hip-width, bar over mid-foot',
      'Hinge at hips and grip bar outside knees',
      'Drive through feet, extending hips and knees',
      'Stand tall at top, then lower with control',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/ErectorSpinae/BBDeadlift',
  },
  {
    exerciseId: 'pull-ups',
    name: 'Pull-Ups',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'bodyweight',
    description: 'Classic bodyweight exercise for lat and back development.',
    instructions: [
      'Hang from bar with overhand grip, slightly wider than shoulders',
      'Pull body up until chin clears the bar',
      'Lower with control to full extension',
      'Avoid swinging or kipping',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/BWPullup',
  },
  {
    exerciseId: 'barbell-rows',
    name: 'Barbell Rows',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms', 'core'],
    equipment: 'barbell',
    description: 'Bent-over row for overall back thickness.',
    instructions: [
      'Hinge forward at hips with slight knee bend',
      'Pull bar to lower chest/upper abdomen',
      'Squeeze shoulder blades together at top',
      'Lower with control, maintaining back position',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/BBBentOverRow',
  },
  {
    exerciseId: 'lat-pulldowns',
    name: 'Lat Pulldowns',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'cable',
    description: 'Cable exercise targeting the latissimus dorsi.',
    instructions: [
      'Sit at lat pulldown machine with thighs secured',
      'Grip bar wider than shoulder-width',
      'Pull bar to upper chest, squeezing lats',
      'Return to full extension with control',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/CBFrontPulldown',
  },
  {
    exerciseId: 'seated-cable-rows',
    name: 'Seated Cable Rows',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'cable',
    description: 'Seated rowing movement for mid-back development.',
    instructions: [
      'Sit with feet on platform, knees slightly bent',
      'Pull handle to lower chest',
      'Squeeze shoulder blades together',
      'Return with control, allowing stretch',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/CBSeatedRow',
  },
  {
    exerciseId: 'dumbbell-rows',
    name: 'Dumbbell Rows',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'dumbbell',
    description: 'One-arm row for unilateral back development.',
    instructions: [
      'Place one hand and knee on bench for support',
      'Hold dumbbell with free hand, arm extended',
      'Pull dumbbell to hip, squeezing shoulder blade',
      'Lower with control to full extension',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/DBBentOverRow',
  },
  {
    exerciseId: 'chin-ups',
    name: 'Chin-Ups',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'bodyweight',
    description: 'Underhand grip pull-up emphasizing biceps and lower lats.',
    instructions: [
      'Hang from bar with underhand (supinated) grip',
      'Pull body up until chin clears the bar',
      'Focus on squeezing lats and biceps',
      'Lower with control to full extension',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/BWUnderhandChinup',
  },

  // BICEPS
  {
    exerciseId: 'bicep-curls',
    name: 'Bicep Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    description: 'Classic isolation exercise for bicep development.',
    instructions: [
      'Stand with dumbbells at sides, palms forward',
      'Curl weights to shoulder level',
      'Squeeze biceps at the top',
      'Lower slowly to full extension',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/DBCurl',
  },
  {
    exerciseId: 'hammer-curls',
    name: 'Hammer Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    description: 'Bicep curl variation targeting the brachialis and forearms.',
    instructions: [
      'Hold dumbbells with neutral grip (palms facing each other)',
      'Curl weights to shoulder level',
      'Keep elbows stationary at sides',
      'Lower with control',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Brachioradialis/DBHammerCurl',
  },
  {
    exerciseId: 'barbell-curls',
    name: 'Barbell Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    description: 'Heavy compound curl using barbell for maximum bicep loading.',
    instructions: [
      'Stand with barbell, underhand grip at shoulder width',
      'Curl bar to shoulder height',
      'Keep upper arms stationary',
      'Lower with control to full extension',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/BBCurl',
  },
  {
    exerciseId: 'incline-dumbbell-curls',
    name: 'Incline Dumbbell Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    description: 'Curl on incline bench for greater bicep stretch under load.',
    instructions: [
      'Sit on incline bench set to 45 degrees',
      'Let arms hang straight down with dumbbells',
      'Curl weights up while keeping upper arms stationary',
      'Lower slowly to full stretch',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/DBInclineCurl',
  },
  {
    exerciseId: 'cable-curls',
    name: 'Cable Curls',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    description: 'Cable curl providing constant tension throughout the range of motion.',
    instructions: [
      'Stand facing cable machine with bar attachment at low position',
      'Grip bar with underhand grip at shoulder width',
      'Curl bar up toward shoulders',
      'Lower with control, maintaining tension',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/CBCurl',
  },
  {
    exerciseId: 'concentration-curls',
    name: 'Concentration Curls',
    category: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Seated single-arm curl for peak bicep contraction.',
    instructions: [
      'Sit on bench with legs apart',
      'Rest elbow against inner thigh',
      'Curl dumbbell up squeezing bicep at top',
      'Lower slowly with full control',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Brachialis/DBConcentrationCurl',
  },

  // QUADRICEPS
  {
    exerciseId: 'squats',
    name: 'Squats',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    description: 'The king of leg exercises for overall lower body development.',
    instructions: [
      'Position bar on upper back, feet shoulder-width',
      'Break at hips and knees simultaneously',
      'Descend until thighs are parallel or below',
      'Drive through feet to stand back up',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BBSquat',
  },
  {
    exerciseId: 'leg-press',
    name: 'Leg Press',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    description: 'Machine exercise for heavy quadricep loading.',
    instructions: [
      'Sit in leg press machine with back flat against pad',
      'Place feet shoulder-width on platform',
      'Lower platform by bending knees to 90 degrees',
      'Press back up without locking knees',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/SL45LegPress',
  },
  {
    exerciseId: 'bulgarian-split-squats',
    name: 'Bulgarian Split Squats',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    description: 'Single-leg squat variation for balanced leg development.',
    instructions: [
      'Place rear foot on bench behind you',
      'Hold dumbbells at sides',
      'Lower until front thigh is parallel to floor',
      'Drive through front heel to stand',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BBSingleLegSplitSquat',
  },
  {
    exerciseId: 'leg-extensions',
    name: 'Leg Extensions',
    category: 'quadriceps',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Machine isolation exercise for quadricep definition.',
    instructions: [
      'Sit in machine with back against pad',
      'Hook ankles under roller pad',
      'Extend legs until straight',
      'Lower with control, avoid letting weight stack slam',
    ],
    tags: ['legs', 'isolation', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/LVLegExtension',
  },
  {
    exerciseId: 'front-squats',
    name: 'Front Squats',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'barbell',
    description: 'Front-loaded squat emphasizing quads and upright torso.',
    instructions: [
      'Rest barbell across front deltoids with crossed arms or clean grip',
      'Keep elbows high and chest up throughout',
      'Squat down until thighs are parallel or below',
      'Drive through feet to stand, maintaining upright torso',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BBFrontSquat',
  },
  {
    exerciseId: 'lunges',
    name: 'Lunges',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    description: 'Walking or stationary lunge for unilateral leg strength.',
    instructions: [
      'Hold dumbbells at sides, stand tall',
      'Step forward into a lunge position',
      'Lower back knee toward floor',
      'Push through front foot to return or step forward',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/DBLunge',
  },
  {
    exerciseId: 'hack-squats',
    name: 'Hack Squats',
    category: 'quadriceps',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    description: 'Machine squat variation for focused quad development.',
    instructions: [
      'Position shoulders under pads, feet shoulder-width on platform',
      'Release safety handles',
      'Lower by bending knees to 90 degrees',
      'Press back up through feet',
    ],
    tags: ['legs', 'compound', 'quadriceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/SLHackSquat',
  },

  // HAMSTRINGS
  {
    exerciseId: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    description: 'Hip hinge movement focusing on hamstring stretch and load.',
    instructions: [
      'Hold barbell with overhand grip at hip level',
      'Hinge at hips, pushing them backward',
      'Lower bar along legs until hamstring stretch is felt',
      'Drive hips forward to return to standing',
    ],
    tags: ['legs', 'compound', 'hamstrings'],
    referenceUrl: 'https://exrx.net/WeightExercises/OlympicLifts/RomanianDeadlift',
  },
  {
    exerciseId: 'leg-curls',
    name: 'Leg Curls',
    category: 'hamstrings',
    secondaryMuscles: ['calves'],
    equipment: 'machine',
    description: 'Machine isolation exercise for hamstring development.',
    instructions: [
      'Lie face down on leg curl machine',
      'Hook heels under roller pad',
      'Curl weight by bending knees',
      'Lower with control to starting position',
    ],
    tags: ['legs', 'isolation', 'hamstrings'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/LVLyingLegCurl',
  },
  {
    exerciseId: 'seated-leg-curls',
    name: 'Seated Leg Curls',
    category: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Seated machine curl for hamstring isolation.',
    instructions: [
      'Sit in machine with back against pad',
      'Position pad above heels, legs extended',
      'Curl legs down by bending knees',
      'Return slowly to starting position',
    ],
    tags: ['legs', 'isolation', 'hamstrings'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/LVSeatedLegCurl',
  },
  {
    exerciseId: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    category: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'dumbbell',
    description: 'Dumbbell variation of the RDL for hamstring and glute work.',
    instructions: [
      'Hold dumbbells at thighs with neutral grip',
      'Hinge at hips pushing them backward',
      'Lower dumbbells along legs keeping back flat',
      'Drive hips forward to return to standing',
    ],
    tags: ['legs', 'compound', 'hamstrings'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/DBStrBackStrLegDeadlift',
  },

  // CALVES
  {
    exerciseId: 'calf-raises',
    name: 'Calf Raises',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Standing calf raise for calf muscle development.',
    instructions: [
      'Stand on calf raise machine with balls of feet on platform',
      'Lower heels below platform for full stretch',
      'Rise up on toes as high as possible',
      'Squeeze at top, lower with control',
    ],
    tags: ['legs', 'isolation', 'calves'],
    referenceUrl: 'https://exrx.net/WeightExercises/Gastrocnemius/LVStandingCalfRaise',
  },
  {
    exerciseId: 'seated-calf-raises',
    name: 'Seated Calf Raises',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Seated calf raise targeting the soleus muscle.',
    instructions: [
      'Sit in seated calf raise machine with knees under pad',
      'Place balls of feet on platform edge',
      'Lower heels for full stretch',
      'Push up through toes and squeeze at top',
    ],
    tags: ['legs', 'isolation', 'calves'],
    referenceUrl: 'https://exrx.net/WeightExercises/Soleus/LVSeatedCalfRaise',
  },
  {
    exerciseId: 'leg-press-calf-raises',
    name: 'Leg Press Calf Raises',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    description: 'Calf raise performed on the leg press machine for heavy loading.',
    instructions: [
      'Sit in leg press with balls of feet on lower edge of platform',
      'Keep legs nearly straight',
      'Push through toes extending ankles',
      'Lower heels back for full stretch',
    ],
    tags: ['legs', 'isolation', 'calves'],
    referenceUrl: 'https://exrx.net/WeightExercises/Gastrocnemius/SL45CalfPress',
  },

  // GLUTES
  {
    exerciseId: 'hip-thrusts',
    name: 'Hip Thrusts',
    category: 'glutes',
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: 'barbell',
    description: 'Barbell hip thrust for maximum glute activation.',
    instructions: [
      'Sit on floor with upper back against bench',
      'Roll barbell over hips with pad',
      'Drive hips up until body forms straight line',
      'Squeeze glutes at top, lower with control',
    ],
    tags: ['legs', 'compound', 'glutes'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/BBHipThrust',
  },
  {
    exerciseId: 'cable-kickbacks',
    name: 'Cable Kickbacks',
    category: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'cable',
    description: 'Cable hip extension for targeted glute isolation.',
    instructions: [
      'Attach ankle cuff to low cable',
      'Face the machine holding frame for support',
      'Kick leg backward squeezing glute at top',
      'Return slowly to starting position',
    ],
    tags: ['legs', 'isolation', 'glutes'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/CBStandingHipExtension',
  },

  // CORE
  {
    exerciseId: 'plank',
    name: 'Plank',
    category: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    description: 'Isometric core exercise for stability and endurance.',
    instructions: [
      'Get in push-up position on forearms',
      'Keep body in straight line from head to heels',
      'Engage core and hold position',
      'Breathe steadily throughout',
    ],
    tags: ['core', 'isometric', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWFrontPlank',
  },
  {
    exerciseId: 'cable-crunches',
    name: 'Cable Crunches',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'cable',
    description: 'Weighted crunch using cable for progressive overload on abs.',
    instructions: [
      'Kneel facing cable machine with rope attachment',
      'Hold rope behind head',
      'Crunch downward, bringing elbows toward knees',
      'Return to starting position with control',
    ],
    tags: ['core', 'isolation', 'abs'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/CBKneelingCrunch',
  },
  {
    exerciseId: 'stability-ball-crunches',
    name: 'Stability Ball Crunches',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Crunches on a stability ball for increased range of motion.',
    instructions: [
      'Lie back on stability ball with feet flat on floor',
      'Place hands behind head or across chest',
      'Crunch up contracting abs',
      'Lower back over ball for full stretch',
    ],
    tags: ['core', 'isolation', 'abs'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWBallCrunch',
  },

  // SYNCED FROM FRONTEND
  {
    exerciseId: 'banded-hip-thrust',
    name: 'Banded Hip Thrust',
    category: 'glutes',
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: 'resistance-band',
    description: 'Hip thrust with resistance band for glute activation.',
    instructions: [
      'Sit with upper back on bench, band around thighs or above knees',
      'Drive through heels to extend hips',
      'Squeeze glutes at top',
      'Lower with control',
    ],
    tags: ['compound', 'glutes', 'resistance-band', 'push'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/BandHipThrust',
  },
  {
    exerciseId: 'banded-squat',
    name: 'Banded Squat',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'resistance-band',
    description: 'Squat with resistance band for added tension and knee tracking.',
    instructions: [
      'Place band above knees, stand with feet shoulder-width',
      'Push knees out against band as you squat',
      'Drive through heels to stand',
      'Keep tension on band throughout',
    ],
    tags: ['compound', 'quadriceps', 'resistance-band', 'push'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BandSquat',
  },
  {
    exerciseId: 'barbell-shrugs',
    name: 'Barbell Shrugs',
    category: 'traps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    description: 'Compound movement targeting the upper trapezius.',
    instructions: [
      "Stand with barbell at arms' length, grip shoulder-width",
      'Shrug shoulders straight up toward ears',
      'Squeeze at the top, lower with control',
      'Avoid rolling shoulders',
    ],
    tags: ['compound', 'traps', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/TrapeziusUpper/BBShrug',
  },
  {
    exerciseId: 'cable-woodchop',
    name: 'Cable Woodchop',
    category: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    description: 'Rotational cable exercise for obliques and core power.',
    instructions: [
      'Set cable at shoulder height, stand sideways',
      'Grip handle with both hands, rotate torso away from cable',
      'Pull across body to opposite hip',
      'Control the return and repeat',
    ],
    tags: ['core', 'obliques', 'rotation', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/Obliques/CBWoodchopper',
  },
  {
    exerciseId: 'dead-bug',
    name: 'Dead Bug',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Core stability exercise with alternating arm and leg extensions.',
    instructions: [
      'Lie on back, arms up, knees bent 90 degrees',
      'Extend opposite arm and leg toward floor',
      'Keep lower back pressed down',
      'Return and alternate sides',
    ],
    tags: ['core', 'stability', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWDeadBug',
  },
  {
    exerciseId: 'dumbbell-shrugs',
    name: 'Dumbbell Shrugs',
    category: 'traps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    description: 'Trap isolation with dumbbells for independent arm movement.',
    instructions: [
      'Stand with dumbbells at sides, palms facing in',
      'Shrug shoulders straight up',
      'Hold at top briefly, lower slowly',
      'Keep arms straight throughout',
    ],
    tags: ['isolation', 'traps', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/TrapeziusUpper/DBShrug',
  },
  {
    exerciseId: 'ez-bar-bicep-curl',
    name: 'EZ-Bar Bicep Curl',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'ez-bar',
    description: 'Bicep curl with EZ bar for wrist comfort and bicep focus.',
    instructions: [
      "Stand with EZ bar at arms' length, palms forward",
      'Curl bar up toward shoulders',
      'Squeeze biceps at top, lower with control',
      'Keep elbows at sides throughout',
    ],
    tags: ['isolation', 'biceps', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/EZBarCurl',
  },
  {
    exerciseId: 'ez-bar-skull-crusher',
    name: 'EZ-Bar Skull Crusher',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'ez-bar',
    description: 'Lying triceps extension with EZ bar for comfortable grip.',
    instructions: [
      'Lie on bench, EZ bar above chest, narrow grip',
      'Lower bar toward forehead by bending elbows',
      'Keep upper arms perpendicular to floor',
      'Extend arms back to start',
    ],
    tags: ['isolation', 'triceps', 'push'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/EZBarLyingTriExt',
  },
  {
    exerciseId: 'farmer-walk',
    name: 'Farmer Walk',
    category: 'forearms',
    secondaryMuscles: ['traps', 'core'],
    equipment: 'dumbbell',
    description: 'Loaded carry for grip, traps, and core stability.',
    instructions: [
      'Hold heavy dumbbells or kettlebells at sides',
      'Walk forward with short steps, standing tall',
      'Keep core tight and shoulders down',
      'Walk for distance or time',
    ],
    tags: ['compound', 'forearms', 'grip', 'carry'],
    referenceUrl: 'https://exrx.net/WeightExercises/TrapeziusUpper/DBFarmerWalk',
  },
  {
    exerciseId: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'glutes',
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: 'bodyweight',
    description: 'Hip extension exercise targeting the glutes and hamstrings.',
    instructions: [
      'Lie on back with knees bent, feet flat',
      'Drive through heels to lift hips toward ceiling',
      'Squeeze glutes at the top',
      'Lower with control',
    ],
    tags: ['isolation', 'glutes', 'push'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/BWBridge',
  },
  {
    exerciseId: 'good-morning',
    name: 'Good Morning',
    category: 'hamstrings',
    secondaryMuscles: ['glutes', 'back', 'core'],
    equipment: 'barbell',
    description: 'Hip hinge exercise for hamstrings and posterior chain.',
    instructions: [
      'Stand with bar on upper back, feet shoulder-width',
      'Hinge at hips, push butt back',
      'Lower until torso near parallel',
      'Drive back up to standing',
    ],
    tags: ['compound', 'hamstrings', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/BBGoodMorning',
  },
  {
    exerciseId: 'hanging-leg-raises',
    name: 'Hanging Leg Raises',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Advanced core exercise lifting legs while hanging from a bar.',
    instructions: [
      'Hang from bar with arms straight',
      'Raise legs until parallel or higher',
      'Lower with control, avoid swinging',
      'Keep core engaged throughout',
    ],
    tags: ['core', 'compound', 'bodyweight', 'abs'],
    referenceUrl: 'https://exrx.net/WeightExercises/Illiopsoas/BWHangingLegHipRaise',
  },
  {
    exerciseId: 'kettlebell-goblet-squat',
    name: 'Kettlebell Goblet Squat',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'kettlebell',
    description: 'Front-loaded squat with kettlebell for quads and core.',
    instructions: [
      'Hold kettlebell at chest, elbows under the bell',
      'Squat down keeping chest up',
      'Drive through heels to stand',
      'Keep core tight throughout',
    ],
    tags: ['compound', 'quadriceps', 'kettlebell', 'push'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/KBGobletSquat',
  },
  {
    exerciseId: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'glutes',
    secondaryMuscles: ['hamstrings', 'core', 'shoulders'],
    equipment: 'kettlebell',
    description: 'Hip-hinge explosive movement for posterior chain and conditioning.',
    instructions: [
      'Hinge at hips, kettlebell between legs',
      'Drive hips forward to swing bell to chest height',
      "Let arms follow, don't lift with arms",
      'Control the downswing and repeat',
    ],
    tags: ['compound', 'glutes', 'kettlebell', 'cardio'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/KBSwing',
  },
  {
    exerciseId: 'pec-deck',
    name: 'Pec Deck',
    category: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'machine',
    description: 'Machine fly for chest isolation and squeeze.',
    instructions: [
      'Sit with back flat, grip handles or place forearms on pads',
      'Bring arms together in front of chest',
      'Squeeze chest at peak',
      'Return slowly to stretch',
    ],
    tags: ['push', 'isolation', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/LVPecFly',
  },
  {
    exerciseId: 'reverse-wrist-curls',
    name: 'Reverse Wrist Curls',
    category: 'forearms',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Isolation exercise for wrist extensors and outer forearms.',
    instructions: [
      'Sit with forearms on bench, palms down, wrists off edge',
      'Curl weight up by extending wrists',
      'Lower with control',
      'Keep upper arms still throughout',
    ],
    tags: ['isolation', 'forearms', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/WristExtensors/DBReverseWristCurl',
  },
  {
    exerciseId: 'russian-twist',
    name: 'Russian Twist',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Rotational core exercise for obliques and stability.',
    instructions: [
      'Sit with feet off floor, knees bent',
      'Hold hands together, rotate torso side to side',
      'Touch floor or weight beside hip each side',
      'Keep movement controlled',
    ],
    tags: ['core', 'obliques', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/Obliques/BWSeatedTwist',
  },
  {
    exerciseId: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Unilateral calf raise for balance and focused calf work.',
    instructions: [
      'Stand on one foot, hold dumbbell in opposite hand',
      'Rise onto ball of foot as high as possible',
      'Lower with full stretch',
      'Switch legs after set',
    ],
    tags: ['isolation', 'calves', 'unilateral', 'push'],
    referenceUrl: 'https://exrx.net/WeightExercises/Gastrocnemius/DBOneLegCalfRaise',
  },
  {
    exerciseId: 'single-leg-hip-thrust',
    name: 'Single-Leg Hip Thrust',
    category: 'glutes',
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: 'bodyweight',
    description: 'Unilateral hip thrust for glute focus and balance.',
    instructions: [
      'Back on bench, one foot flat, other leg extended',
      'Drive through planted foot to lift hips',
      'Squeeze glute at top, lower slowly',
      'Switch legs after set',
    ],
    tags: ['isolation', 'glutes', 'unilateral', 'push'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/BWOneLegBridge',
  },
  {
    exerciseId: 'smith-machine-bench-press',
    name: 'Smith Machine Bench Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'smith-machine',
    description: 'Bench press on Smith machine for controlled bar path.',
    instructions: [
      'Lie on bench under Smith bar, grip slightly wider than shoulders',
      'Unrack and lower bar to mid-chest',
      'Press up to lockout',
      'Keep feet flat on floor',
    ],
    tags: ['push', 'compound', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/SMBenchPress',
  },
  {
    exerciseId: 'smith-machine-incline-press',
    name: 'Smith Machine Incline Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'smith-machine',
    description: 'Incline press on Smith machine for upper chest.',
    instructions: [
      'Set bench to 30-45 degrees under Smith bar',
      'Unrack and lower bar to upper chest',
      'Press up to lockout',
      'Keep control throughout',
    ],
    tags: ['push', 'compound', 'upper-chest', 'chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralClavicular/SMInclineBenchPress',
  },
  {
    exerciseId: 'stiff-leg-deadlift',
    name: 'Stiff-Leg Deadlift',
    category: 'hamstrings',
    secondaryMuscles: ['glutes', 'back', 'core'],
    equipment: 'barbell',
    description: 'Deadlift variation with straighter legs to emphasize hamstrings.',
    instructions: [
      'Stand with bar in front, slight knee bend',
      'Hinge at hips and lower bar along legs',
      'Feel hamstring stretch at bottom',
      'Return to standing by driving hips forward',
    ],
    tags: ['compound', 'hamstrings', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/BBStiffLegDeadlift',
  },
  {
    exerciseId: 'straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    category: 'back',
    secondaryMuscles: [],
    equipment: 'cable',
    description: 'Lat isolation with straight arms for stretch and contraction.',
    instructions: [
      'Stand facing cable, bar attachment, arms straight',
      'Pull bar down to thighs using lats',
      'Keep arms straight, slight bend in elbows',
      'Return slowly for stretch',
    ],
    tags: ['pull', 'isolation', 'back', 'lats'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/CBStraightArmPulldown',
  },
  {
    exerciseId: 't-bar-row',
    name: 'T-Bar Row',
    category: 'back',
    secondaryMuscles: ['biceps', 'traps'],
    equipment: 'barbell',
    description: 'Bent-over row using T-bar or landmine for mid-back thickness.',
    instructions: [
      'Stand over the bar, hinge at hips, grip the handle',
      'Pull handle toward lower chest',
      'Squeeze shoulder blades together',
      'Lower with control',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/TBarRow',
  },
  {
    exerciseId: 'upright-row',
    name: 'Upright Row',
    category: 'traps',
    secondaryMuscles: ['shoulders', 'biceps'],
    equipment: 'barbell',
    description: 'Vertical pull for traps and lateral deltoids.',
    instructions: [
      'Stand with bar at thighs, grip slightly narrower than shoulder-width',
      'Pull bar up toward chin, elbows high',
      'Lower with control',
      'Keep bar close to body',
    ],
    tags: ['pull', 'compound', 'traps', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/TrapeziusUpper/BBUprightRow',
  },
  {
    exerciseId: 'wrist-curls',
    name: 'Wrist Curls',
    category: 'forearms',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Isolation exercise for wrist flexors and forearm development.',
    instructions: [
      'Sit with forearms on bench, palms up, wrists off edge',
      'Curl weight up by flexing wrists',
      'Lower with control for full stretch',
      'Keep upper arms still throughout',
    ],
    tags: ['isolation', 'forearms', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/WristFlexors/DBWristCurl',
  },

  // NEW CHEST
  {
    exerciseId: 'incline-barbell-press',
    name: 'Incline Barbell Press',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    description: 'Upper chest barbell press on an inclined bench.',
    instructions: [
      'Set bench to 30-45 degree incline',
      'Grip bar slightly wider than shoulder-width',
      'Lower bar to upper chest with control',
      'Press back up to full extension',
    ],
    tags: ['push', 'compound', 'upper-chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralClavicular/BBInclineBenchPress',
  },
  {
    exerciseId: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    category: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    description: 'Bench press with narrow grip to target inner chest and triceps.',
    instructions: [
      'Lie on flat bench, grip bar shoulder-width or narrower',
      'Lower bar to mid-chest with elbows tucked',
      'Press back up to lockout',
      'Keep core tight and feet flat',
    ],
    tags: ['push', 'compound', 'chest', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/BBCloseGripBenchPress',
  },
  {
    exerciseId: 'high-to-low-cable-flyes',
    name: 'High-to-Low Cable Flyes',
    category: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'cable',
    description: 'Cable fly from high to low to target the lower chest.',
    instructions: [
      'Set cables above shoulder height',
      'Step forward, lean slightly',
      'Pull handles down and together toward hips',
      'Squeeze lower chest at bottom, return slowly',
    ],
    tags: ['push', 'isolation', 'chest', 'lower-chest'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/CBDeclineFly',
  },
  {
    exerciseId: 'landmine-press',
    name: 'Landmine Press',
    category: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell',
    description: 'Single-arm angled press for upper chest and shoulder development.',
    instructions: [
      'Secure one end of barbell in corner or landmine attachment',
      'Hold the other end at shoulder level',
      'Press bar up and forward in an arc',
      'Lower with control to starting position',
    ],
    tags: ['push', 'compound', 'chest', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralClavicular/BBLandminePress',
  },
  {
    exerciseId: 'incline-push-ups',
    name: 'Incline Push-Ups',
    category: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    description: 'Push-ups with hands elevated for lower chest emphasis.',
    instructions: [
      'Place hands on bench or elevated surface',
      'Body in straight line from head to heels',
      'Lower chest to surface by bending elbows',
      'Push back up to full extension',
    ],
    tags: ['push', 'compound', 'chest', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/PectoralSternal/BWInclinePushup',
  },

  // NEW BACK
  {
    exerciseId: 'meadows-row',
    name: 'Meadows Row',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'barbell',
    description: 'Single-arm landmine row for lat thickness and upper back.',
    instructions: [
      'Stand perpendicular to loaded barbell end',
      'Hinge forward and grip the end with one hand',
      'Row the weight up toward your hip',
      'Lower with control and repeat',
    ],
    tags: ['pull', 'compound', 'back', 'unilateral'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/BBMeadowsRow',
  },
  {
    exerciseId: 'chest-supported-dumbbell-row',
    name: 'Chest-Supported Dumbbell Row',
    category: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    description: 'Incline bench row eliminating lower back stress.',
    instructions: [
      'Lie face down on incline bench at 45 degrees',
      'Hold dumbbells hanging below bench',
      'Row both dumbbells up, squeezing shoulder blades',
      'Lower with control',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/DBInclineSupportedRow',
  },
  {
    exerciseId: 'inverted-row',
    name: 'Inverted Row',
    category: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    description: 'Horizontal pull using bodyweight on a bar or rings.',
    instructions: [
      'Set bar at waist height, hang underneath with arms extended',
      'Keep body straight from heels to head',
      'Pull chest up to the bar',
      'Lower slowly to full extension',
    ],
    tags: ['pull', 'compound', 'back', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/BackGeneral/BWInvertedRow',
  },
  {
    exerciseId: 'single-arm-cable-row',
    name: 'Single-Arm Cable Row',
    category: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    description: 'Unilateral cable row for back width and core stability.',
    instructions: [
      'Attach single handle to low cable',
      'Sit or stand, pull handle to side of torso',
      'Squeeze shoulder blade at end position',
      'Lower with control and repeat',
    ],
    tags: ['pull', 'compound', 'back', 'unilateral'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/CBOneArmRow',
  },
  {
    exerciseId: 'rack-pull',
    name: 'Rack Pull',
    category: 'back',
    secondaryMuscles: ['traps', 'hamstrings'],
    equipment: 'barbell',
    description: 'Partial deadlift from knee height for upper back and trap overload.',
    instructions: [
      'Set bar in rack at knee height',
      'Grip bar outside knees with overhand or mixed grip',
      'Drive hips forward, standing tall',
      'Lower bar back to rack with control',
    ],
    tags: ['pull', 'compound', 'back', 'traps'],
    referenceUrl: 'https://exrx.net/WeightExercises/ErectorSpinae/BBRackPull',
  },
  {
    exerciseId: 'close-grip-lat-pulldown',
    name: 'Close-Grip Lat Pulldown',
    category: 'back',
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: 'cable',
    description: 'Lat pulldown with narrow grip to increase lat stretch.',
    instructions: [
      'Sit at lat pulldown machine with thighs secured',
      'Grip bar or V-bar at shoulder-width or narrower',
      'Pull to upper chest, elbows tucked',
      'Return to full extension with control',
    ],
    tags: ['pull', 'compound', 'back'],
    referenceUrl: 'https://exrx.net/WeightExercises/LatissimusDorsi/CBCloseGripPulldown',
  },

  // NEW SHOULDERS
  {
    exerciseId: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'shoulders',
    secondaryMuscles: ['traps'],
    equipment: 'cable',
    description: 'Lateral raise with cable for constant tension on lateral delts.',
    instructions: [
      'Stand sideways to cable machine, low attachment',
      'Grip handle with far hand, arm at side',
      'Raise arm out to side until parallel to floor',
      'Lower slowly with control',
    ],
    tags: ['push', 'isolation', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidLateral/CBLateralRaise',
  },
  {
    exerciseId: 'machine-overhead-press',
    name: 'Machine Overhead Press',
    category: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    description: 'Seated machine shoulder press for controlled deltoid development.',
    instructions: [
      'Adjust seat so handles are at shoulder height',
      'Grip handles and press overhead until arms extended',
      'Lower with control to starting position',
      'Keep back flat against pad',
    ],
    tags: ['push', 'compound', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/LVShoulderPress',
  },
  {
    exerciseId: 'cable-front-raise',
    name: 'Cable Front Raise',
    category: 'shoulders',
    secondaryMuscles: [],
    equipment: 'cable',
    description: 'Front raise with cable for constant tension on anterior delts.',
    instructions: [
      'Stand facing away from low cable, grip handle',
      'Raise arm straight forward to shoulder height',
      'Lower slowly with control',
      'Alternate arms or perform bilaterally',
    ],
    tags: ['push', 'isolation', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/CBFrontRaise',
  },
  {
    exerciseId: 'pike-push-up',
    name: 'Pike Push-Up',
    category: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'bodyweight',
    description: 'Bodyweight shoulder press variation in a pike position.',
    instructions: [
      'Start in downward dog position, hips high',
      'Bend elbows to lower head toward floor',
      'Press back up to full arm extension',
      'Keep hips high throughout',
    ],
    tags: ['push', 'compound', 'shoulders', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidAnterior/BWPikePushup',
  },
  {
    exerciseId: 'band-pull-apart',
    name: 'Band Pull-Apart',
    category: 'shoulders',
    secondaryMuscles: ['traps'],
    equipment: 'resistance-band',
    description: 'Rear delt and upper back activation with resistance band.',
    instructions: [
      'Hold band at chest height with arms extended',
      'Pull band apart, spreading hands to sides',
      'Squeeze shoulder blades at end position',
      'Return slowly to starting position',
    ],
    tags: ['pull', 'isolation', 'rear-delts', 'shoulders'],
    referenceUrl: 'https://exrx.net/WeightExercises/DeltoidPosterior/BandPullApart',
  },

  // NEW BICEPS
  {
    exerciseId: 'preacher-curl',
    name: 'Preacher Curl',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    description: 'Strict curl on preacher bench for peak bicep isolation.',
    instructions: [
      'Sit at preacher bench with arms over the pad',
      'Hold barbell or EZ bar with underhand grip',
      'Curl weight up fully contracting biceps',
      'Lower slowly for full stretch',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/BBPreacherCurl',
  },
  {
    exerciseId: 'spider-curl',
    name: 'Spider Curl',
    category: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Prone incline curl for peak bicep contraction.',
    instructions: [
      'Lie face down on incline bench, arms hanging',
      'Curl dumbbells up squeezing biceps',
      'Lower with control to full extension',
      'Keep upper arms still throughout',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Biceps/DBSpiderCurl',
  },
  {
    exerciseId: 'cable-hammer-curl',
    name: 'Cable Hammer Curl',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    description: 'Hammer curl variation using rope cable for constant tension.',
    instructions: [
      'Attach rope to low cable, stand facing machine',
      'Grip rope with neutral grip, palms facing each other',
      'Curl up to shoulder level',
      'Lower with control, maintaining tension',
    ],
    tags: ['pull', 'isolation', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Brachioradialis/CBHammerCurl',
  },
  {
    exerciseId: 'reverse-barbell-curl',
    name: 'Reverse Barbell Curl',
    category: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    description: 'Overhand curl targeting the brachialis and forearms.',
    instructions: [
      'Stand with barbell, overhand grip at shoulder width',
      'Curl bar up toward shoulders',
      'Keep elbows pinned to sides',
      'Lower with control to full extension',
    ],
    tags: ['pull', 'isolation', 'biceps', 'forearms'],
    referenceUrl: 'https://exrx.net/WeightExercises/Brachioradialis/BBReverseCurl',
  },

  // NEW TRICEPS
  {
    exerciseId: 'cable-overhead-tricep-extension',
    name: 'Cable Overhead Tricep Extension',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    description: 'Overhead tricep extension with cable for constant tension on long head.',
    instructions: [
      'Attach rope to high cable, face away from machine',
      'Hold rope behind head with elbows bent',
      'Extend arms overhead, squeezing triceps',
      'Lower behind head with control',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/CBOverheadTricepExt',
  },
  {
    exerciseId: 'single-arm-cable-pushdown',
    name: 'Single-Arm Cable Pushdown',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    description: 'Unilateral tricep pushdown for balanced development.',
    instructions: [
      'Stand facing cable machine with single handle attachment',
      'Keep elbow pinned to side',
      'Push handle down until arm fully extended',
      'Return slowly to starting position',
    ],
    tags: ['push', 'isolation', 'triceps', 'unilateral'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/CBOneArmPushdown',
  },
  {
    exerciseId: 'bench-dips',
    name: 'Bench Dips',
    category: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'bodyweight',
    description: 'Tricep dips performed with hands on a bench.',
    instructions: [
      'Sit on edge of bench, hands beside hips',
      'Slide hips off bench, legs extended',
      'Lower body by bending elbows to 90 degrees',
      'Push back up to starting position',
    ],
    tags: ['push', 'compound', 'triceps', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/BWBenchDip',
  },
  {
    exerciseId: 'lying-dumbbell-extension',
    name: 'Lying Dumbbell Extension',
    category: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Dumbbell variation of skull crushers for tricep isolation.',
    instructions: [
      'Lie on flat bench, dumbbells above chest',
      'Lower dumbbells toward temples by bending elbows',
      'Keep upper arms perpendicular to floor',
      'Extend arms back to starting position',
    ],
    tags: ['push', 'isolation', 'triceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Triceps/DBLyingTriExt',
  },

  // NEW QUADRICEPS
  {
    exerciseId: 'step-ups',
    name: 'Step-Ups',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    description: 'Unilateral leg exercise stepping onto a box or bench.',
    instructions: [
      'Hold dumbbells at sides, stand in front of box',
      'Step up with one foot, driving through heel',
      'Stand tall on box, then step down',
      'Alternate legs or complete a set per side',
    ],
    tags: ['legs', 'compound', 'quadriceps', 'unilateral'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/DBStepUp',
  },
  {
    exerciseId: 'dumbbell-sumo-squat',
    name: 'Dumbbell Sumo Squat',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'dumbbell',
    description: 'Wide-stance squat with dumbbell for inner thigh and glute focus.',
    instructions: [
      'Hold dumbbell vertically at chest or between legs',
      'Stand with feet wider than shoulder-width, toes out',
      'Squat down keeping chest up',
      'Drive through heels to stand',
    ],
    tags: ['legs', 'compound', 'quadriceps', 'glutes'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/DBSumoSquat',
  },
  {
    exerciseId: 'wall-sit',
    name: 'Wall Sit',
    category: 'quadriceps',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'bodyweight',
    description: 'Isometric quad exercise holding a seated position against the wall.',
    instructions: [
      'Stand with back against wall, feet hip-width',
      'Slide down until thighs are parallel to floor',
      'Keep knees at 90 degrees and back flat',
      'Hold position for target time',
    ],
    tags: ['legs', 'isometric', 'quadriceps', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BWWallSit',
  },
  {
    exerciseId: 'sissy-squat',
    name: 'Sissy Squat',
    category: 'quadriceps',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Advanced quad isolation exercise with backward lean.',
    instructions: [
      'Stand holding support, feet close together',
      'Rise onto toes, lean backward as you lower',
      'Bend knees bringing them forward toward floor',
      'Drive back up by extending knees',
    ],
    tags: ['legs', 'isolation', 'quadriceps', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/Quadriceps/BWSissySquat',
  },

  // NEW HAMSTRINGS
  {
    exerciseId: 'nordic-curl',
    name: 'Nordic Curl',
    category: 'hamstrings',
    secondaryMuscles: ['glutes'],
    equipment: 'bodyweight',
    description: 'Eccentric hamstring exercise with ankles anchored.',
    instructions: [
      'Kneel on pad with ankles secured under a bar or held by partner',
      'Lower torso forward toward floor using hamstrings',
      'Use hands to catch yourself at the bottom',
      'Pull back up using hamstrings',
    ],
    tags: ['legs', 'compound', 'hamstrings', 'eccentric'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/BWNordicHamstringCurl',
  },
  {
    exerciseId: 'swiss-ball-leg-curl',
    name: 'Swiss Ball Leg Curl',
    category: 'hamstrings',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'bodyweight',
    description: 'Hamstring curl using a stability ball for core engagement.',
    instructions: [
      'Lie on back, heels on stability ball, hips raised',
      'Pull ball toward glutes by bending knees',
      'Extend legs back out slowly',
      'Keep hips elevated throughout',
    ],
    tags: ['legs', 'compound', 'hamstrings', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/BWBallLegCurl',
  },
  {
    exerciseId: 'cable-pull-through',
    name: 'Cable Pull-Through',
    category: 'hamstrings',
    secondaryMuscles: ['glutes'],
    equipment: 'cable',
    description: 'Hip hinge movement using cable for posterior chain development.',
    instructions: [
      'Stand facing away from low cable, rope between legs',
      'Hinge at hips pushing them back',
      'Drive hips forward to stand pulling rope through',
      'Squeeze glutes at lockout',
    ],
    tags: ['legs', 'compound', 'hamstrings', 'glutes'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/CBPullThrough',
  },
  {
    exerciseId: 'single-leg-dumbbell-deadlift',
    name: 'Single-Leg Dumbbell Deadlift',
    category: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'dumbbell',
    description: 'Single-leg hinge for hamstring and balance development.',
    instructions: [
      'Stand on one leg, hold dumbbell in opposite hand',
      'Hinge forward at hip, extending free leg back',
      'Lower dumbbell toward floor',
      'Return to standing, squeezing glute',
    ],
    tags: ['legs', 'compound', 'hamstrings', 'unilateral'],
    referenceUrl: 'https://exrx.net/WeightExercises/Hamstrings/DBOneLegDeadlift',
  },

  // NEW GLUTES
  {
    exerciseId: 'donkey-kicks',
    name: 'Donkey Kicks',
    category: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'bodyweight',
    description: 'Quadruped hip extension for glute isolation.',
    instructions: [
      'Start on hands and knees, core tight',
      'Kick one leg back and up, squeezing glute',
      'Keep knee bent at 90 degrees',
      'Lower and repeat, then switch legs',
    ],
    tags: ['legs', 'isolation', 'glutes', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/BWDonkeyKick',
  },
  {
    exerciseId: 'frog-pump',
    name: 'Frog Pump',
    category: 'glutes',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'High-rep glute pump with externally rotated legs.',
    instructions: [
      'Lie on back, soles of feet together, knees out',
      'Push hips up contracting glutes hard',
      'Lower slightly and repeat for high reps',
      'Keep feet together throughout',
    ],
    tags: ['legs', 'isolation', 'glutes', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/BWFrogPump',
  },
  {
    exerciseId: 'clamshell',
    name: 'Clamshell',
    category: 'glutes',
    secondaryMuscles: [],
    equipment: 'resistance-band',
    description: 'Hip abduction exercise for glute medius activation.',
    instructions: [
      'Lie on side with knees bent at 45 degrees, band above knees',
      'Keep feet together, rotate top knee upward',
      'Open as far as possible without rotating pelvis',
      'Lower with control and repeat',
    ],
    tags: ['legs', 'isolation', 'glutes', 'abduction'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMedius/BWClamshell',
  },
  {
    exerciseId: 'lateral-band-walk',
    name: 'Lateral Band Walk',
    category: 'glutes',
    secondaryMuscles: ['quadriceps'],
    equipment: 'resistance-band',
    description: 'Side-stepping with resistance band for glute medius activation.',
    instructions: [
      'Place band above ankles or knees, slight squat position',
      'Step sideways, maintaining tension on band',
      'Keep toes forward and knees tracking over toes',
      'Walk for steps in each direction',
    ],
    tags: ['legs', 'isolation', 'glutes', 'abduction'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMedius/BandLateralWalk',
  },
  {
    exerciseId: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    category: 'glutes',
    secondaryMuscles: ['hamstrings', 'back', 'quadriceps'],
    equipment: 'barbell',
    description: 'Wide-stance deadlift emphasizing glutes and inner thighs.',
    instructions: [
      'Stand with feet wider than shoulder-width, toes pointing out',
      'Grip bar between legs, hips low',
      'Drive through heels, extending hips and knees',
      'Stand tall at top, then lower with control',
    ],
    tags: ['legs', 'compound', 'glutes', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/GluteusMaximus/BBSumoDeadlift',
  },

  // NEW CALVES
  {
    exerciseId: 'donkey-calf-raises',
    name: 'Donkey Calf Raises',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Bent-over calf raise for deep stretch and gastrocnemius loading.',
    instructions: [
      'Bend over at 90 degrees, hands on support, balls of feet on edge',
      'Lower heels for maximum stretch',
      'Rise up on toes as high as possible',
      'Squeeze calves at top, lower with control',
    ],
    tags: ['legs', 'isolation', 'calves'],
    referenceUrl: 'https://exrx.net/WeightExercises/Gastrocnemius/BWBentKneeDonkeyCalfRaise',
  },
  {
    exerciseId: 'standing-dumbbell-calf-raises',
    name: 'Standing Dumbbell Calf Raises',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    description: 'Standing calf raise holding dumbbells for added resistance.',
    instructions: [
      'Stand on edge of step holding dumbbells at sides',
      'Lower heels below step level for full stretch',
      'Rise onto toes as high as possible',
      'Squeeze calves at top and lower with control',
    ],
    tags: ['legs', 'isolation', 'calves'],
    referenceUrl: 'https://exrx.net/WeightExercises/Gastrocnemius/DBStandingCalfRaise',
  },
  {
    exerciseId: 'tibialis-raise',
    name: 'Tibialis Raise',
    category: 'calves',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Shin strengthening exercise for ankle stability and balance.',
    instructions: [
      'Stand with back against wall, heels 12 inches out',
      'Lift toes and forefeet as high as possible',
      'Lower slowly to the floor',
      'Repeat for target reps',
    ],
    tags: ['legs', 'isolation', 'calves', 'anterior'],
    referenceUrl: 'https://exrx.net/WeightExercises/TibialisAnterior/BWTibialisRaise',
  },

  // NEW CORE
  {
    exerciseId: 'side-plank',
    name: 'Side Plank',
    category: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    description: 'Lateral isometric core exercise for obliques and stability.',
    instructions: [
      'Lie on side, prop up on forearm directly below shoulder',
      'Stack feet or stagger for balance',
      'Raise hips until body forms straight line',
      'Hold position for target time',
    ],
    tags: ['core', 'isometric', 'obliques', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/Obliques/BWSidePlank',
  },
  {
    exerciseId: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    category: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    description: 'Advanced core stability exercise using an ab wheel.',
    instructions: [
      'Kneel with ab wheel in front, arms extended',
      'Roll forward slowly lowering body toward floor',
      'Extend as far as core can control',
      'Pull wheel back using core and lats',
    ],
    tags: ['core', 'compound', 'bodyweight', 'abs'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWAbWheelRollout',
  },
  {
    exerciseId: 'v-ups',
    name: 'V-Ups',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Full range abs exercise bringing hands and feet together.',
    instructions: [
      'Lie flat on back, arms and legs extended',
      'Simultaneously raise legs and torso',
      'Reach hands toward feet at the top',
      'Lower with control to starting position',
    ],
    tags: ['core', 'isolation', 'abs', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWVUp',
  },
  {
    exerciseId: 'bicycle-crunches',
    name: 'Bicycle Crunches',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Dynamic crunch targeting obliques and rectus abdominis.',
    instructions: [
      'Lie on back, hands behind head, knees bent',
      'Bring opposite elbow to opposite knee',
      'Extend other leg straight while rotating',
      'Alternate sides in a pedaling motion',
    ],
    tags: ['core', 'obliques', 'abs', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/Obliques/BWBicycleCrunch',
  },
  {
    exerciseId: 'mountain-climbers',
    name: 'Mountain Climbers',
    category: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    description: 'Dynamic core exercise combining plank position with running motion.',
    instructions: [
      'Start in high plank position',
      'Drive one knee toward chest',
      'Quickly alternate legs in running motion',
      'Keep hips level and core tight',
    ],
    tags: ['core', 'cardio', 'compound', 'bodyweight'],
    referenceUrl: 'https://exrx.net/WeightExercises/Illiopsoas/BWMountainClimber',
  },
  {
    exerciseId: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    category: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Gymnastics-based isometric core exercise for full core engagement.',
    instructions: [
      'Lie on back, arms extended overhead',
      'Press lower back into floor and lift shoulders and legs',
      'Create a hollow dish shape with your body',
      'Hold position with steady breathing',
    ],
    tags: ['core', 'isometric', 'bodyweight', 'abs'],
    referenceUrl: 'https://exrx.net/WeightExercises/RectusAbdominis/BWHollowBodyHold',
  },

  // NEW FOREARMS
  {
    exerciseId: 'reverse-curl',
    name: 'Reverse Curl',
    category: 'forearms',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    description: 'Overhand grip curl targeting brachioradialis and forearm extensors.',
    instructions: [
      'Stand with barbell, overhand grip shoulder-width',
      'Curl bar up keeping elbows at sides',
      'Lower with control to full extension',
      'Maintain overhand grip throughout',
    ],
    tags: ['pull', 'isolation', 'forearms'],
    referenceUrl: 'https://exrx.net/WeightExercises/Brachioradialis/BBReverseCurl',
  },
  {
    exerciseId: 'zottman-curl',
    name: 'Zottman Curl',
    category: 'forearms',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    description: 'Combination curl targeting both biceps and forearm extensors.',
    instructions: [
      'Stand with dumbbells, palms up (supinated grip)',
      'Curl up to shoulder level squeezing biceps',
      'Rotate to overhand grip at the top',
      'Lower slowly with overhand grip, then rotate back',
    ],
    tags: ['pull', 'isolation', 'forearms', 'biceps'],
    referenceUrl: 'https://exrx.net/WeightExercises/Brachioradialis/DBZottmanCurl',
  },
  {
    exerciseId: 'plate-pinch',
    name: 'Plate Pinch',
    category: 'forearms',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    description: 'Grip strength exercise pinching weight plates with fingers.',
    instructions: [
      'Pinch one or two plates between thumb and fingers',
      'Hold for target time or distance',
      'Keep wrist neutral and arm at side',
      'Alternate hands or hold bilaterally',
    ],
    tags: ['isolation', 'forearms', 'grip'],
    referenceUrl: 'https://exrx.net/WeightExercises/WristFlexors/BWPlatePinch',
  },

  // NEW TRAPS
  {
    exerciseId: 'cable-shrugs',
    name: 'Cable Shrugs',
    category: 'traps',
    secondaryMuscles: ['forearms'],
    equipment: 'cable',
    description: 'Trap isolation using cable for constant tension throughout movement.',
    instructions: [
      'Stand facing cable machine, bar at low position',
      'Grip bar with overhand grip, arms straight',
      'Shrug shoulders straight up toward ears',
      'Hold briefly at top, lower with control',
    ],
    tags: ['isolation', 'traps', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/TrapeziusUpper/CBShrug',
  },
  {
    exerciseId: 'behind-back-shrugs',
    name: 'Behind-Back Shrugs',
    category: 'traps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    description: 'Shrug with bar behind body for different trap emphasis.',
    instructions: [
      'Stand with barbell behind back at arms length',
      'Shrug shoulders straight up',
      'Squeeze traps at top, lower with control',
      'Keep arms straight throughout',
    ],
    tags: ['isolation', 'traps', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/TrapeziusUpper/BBBehindBackShrug',
  },
  {
    exerciseId: 'power-clean',
    name: 'Power Clean',
    category: 'traps',
    secondaryMuscles: ['back', 'shoulders', 'quadriceps', 'hamstrings'],
    equipment: 'barbell',
    description: 'Olympic-style explosive lift for full body power and trap development.',
    instructions: [
      'Start in deadlift position, bar over mid-foot',
      'Explosively pull bar upward, shrugging shoulders',
      'Drop under bar catching it on front deltoids',
      'Stand to finish with bar at shoulder height',
    ],
    tags: ['compound', 'traps', 'explosive', 'pull'],
    referenceUrl: 'https://exrx.net/WeightExercises/OlympicLifts/PowerClean',
  },
];

module.exports = exercises;
