const routines = [
  {
    routineId: 'push',
    name: { en: 'Push', es: 'Empuje' },
    description: {
      en: 'Chest, shoulders, and triceps focused workout',
      es: 'Entrenamiento enfocado en pecho, hombros y tríceps',
    },
    color: '#FF6B6B',
    icon: '💪',
    exercises: [
      {
        exerciseId: 'bench-press',
        sets: 4,
        reps: 12,
        restTimeSeconds: 120,
        notes: 'Focus on controlled eccentric',
      },
      {
        exerciseId: 'incline-dumbbell-press',
        sets: 4,
        reps: 12,
        restTimeSeconds: 120,
        notes: 'Set bench to 30 degrees',
      },
      {
        exerciseId: 'overhead-press',
        sets: 4,
        reps: 10,
        restTimeSeconds: 120,
        notes: 'Keep core tight, avoid leaning back',
      },
      {
        exerciseId: 'lateral-raises',
        sets: 4,
        reps: 15,
        restTimeSeconds: 90,
        notes: 'Light weight, focus on form',
      },
      { exerciseId: 'tricep-pushdowns', sets: 4, reps: 12, restTimeSeconds: 90 },
      { exerciseId: 'overhead-tricep-extension', sets: 3, reps: 12, restTimeSeconds: 90 },
      {
        exerciseId: 'cable-flyes',
        sets: 3,
        reps: 15,
        restTimeSeconds: 90,
        notes: 'Squeeze at peak contraction',
      },
    ],
  },
  {
    routineId: 'pull',
    name: { en: 'Pull', es: 'Jalón' },
    description: {
      en: 'Back and biceps focused workout',
      es: 'Entrenamiento enfocado en espalda y bíceps',
    },
    color: '#4ECDC4',
    icon: '🏋️',
    exercises: [
      {
        exerciseId: 'deadlift',
        sets: 4,
        reps: 8,
        restTimeSeconds: 180,
        notes: 'Warm up thoroughly, maintain neutral spine',
      },
      {
        exerciseId: 'pull-ups',
        sets: 4,
        reps: 10,
        restTimeSeconds: 120,
        notes: 'Full range of motion, no kipping',
      },
      {
        exerciseId: 'barbell-rows',
        sets: 4,
        reps: 12,
        restTimeSeconds: 120,
        notes: 'Keep torso at 45 degrees',
      },
      { exerciseId: 'lat-pulldowns', sets: 4, reps: 12, restTimeSeconds: 90 },
      {
        exerciseId: 'face-pulls',
        sets: 4,
        reps: 15,
        restTimeSeconds: 90,
        notes: 'Great for shoulder health',
      },
      { exerciseId: 'bicep-curls', sets: 4, reps: 12, restTimeSeconds: 90 },
      { exerciseId: 'hammer-curls', sets: 3, reps: 12, restTimeSeconds: 90 },
    ],
  },
  {
    routineId: 'legs',
    name: { en: 'Legs', es: 'Piernas' },
    description: {
      en: 'Quadriceps, hamstrings, glutes, and calves workout',
      es: 'Entrenamiento de cuádriceps, isquiotibiales, glúteos y pantorrillas',
    },
    color: '#FFE66D',
    icon: '🦵',
    exercises: [
      {
        exerciseId: 'squats',
        sets: 4,
        reps: 10,
        restTimeSeconds: 180,
        notes: 'Warm up with lighter sets first',
      },
      {
        exerciseId: 'romanian-deadlift',
        sets: 4,
        reps: 12,
        restTimeSeconds: 120,
        notes: 'Feel the hamstring stretch',
      },
      { exerciseId: 'leg-press', sets: 4, reps: 12, restTimeSeconds: 120 },
      {
        exerciseId: 'bulgarian-split-squats',
        sets: 3,
        reps: 10,
        restTimeSeconds: 120,
        notes: 'Per leg',
      },
      { exerciseId: 'leg-curls', sets: 4, reps: 12, restTimeSeconds: 90 },
      { exerciseId: 'leg-extensions', sets: 4, reps: 12, restTimeSeconds: 90 },
      {
        exerciseId: 'calf-raises',
        sets: 4,
        reps: 15,
        restTimeSeconds: 60,
        notes: 'Full range of motion, pause at top',
      },
    ],
  },
  {
    routineId: 'full-body',
    name: { en: 'Full Body', es: 'Cuerpo Completo' },
    description: {
      en: 'Complete full body workout hitting all major muscle groups',
      es: 'Entrenamiento completo que trabaja todos los grupos musculares principales',
    },
    color: '#A78BFA',
    icon: '⚡',
    exercises: [
      { exerciseId: 'squats', sets: 4, reps: 10, restTimeSeconds: 150 },
      { exerciseId: 'bench-press', sets: 4, reps: 10, restTimeSeconds: 120 },
      { exerciseId: 'barbell-rows', sets: 4, reps: 12, restTimeSeconds: 120 },
      { exerciseId: 'overhead-press', sets: 3, reps: 10, restTimeSeconds: 120 },
      { exerciseId: 'romanian-deadlift', sets: 3, reps: 12, restTimeSeconds: 120 },
      { exerciseId: 'pull-ups', sets: 3, reps: 10, restTimeSeconds: 90 },
      { exerciseId: 'bicep-curls', sets: 3, reps: 12, restTimeSeconds: 90 },
      {
        exerciseId: 'plank',
        sets: 3,
        reps: 60,
        restTimeSeconds: 60,
        notes: 'Hold for 60 seconds per set',
      },
    ],
  },
];

module.exports = routines;
